//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quoc_2210900119.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTQ_SACH
    {
        public string Ntq_MaSach { get; set; }
        public string Ntq_TenSach { get; set; }
        public Nullable<int> Ntq_SoTrang { get; set; }
        public Nullable<int> Ntq_NamXB { get; set; }
        public string Ntq_MaTG { get; set; }
        public Nullable<bool> Ntq_TrangThai { get; set; }
    
        public virtual NTQ_TACGIA NTQ_TACGIA { get; set; }
    }
}
