//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quoc_2210900119.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTQ_TACGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NTQ_TACGIA()
        {
            this.NTQ_SACH = new HashSet<NTQ_SACH>();
        }
    
        public string Ntq_MaTG { get; set; }
        public string Ntq_TenTG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NTQ_SACH> NTQ_SACH { get; set; }
    }
}
