//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtqBaiKiemTraGiuaKi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ntqKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ntqKhoa()
        {
            this.ntqSinhVien = new HashSet<ntqSinhVien>();
        }
    
        public string NtqMaKH { get; set; }
        public string NtqTenKH { get; set; }
        public Nullable<bool> NtqTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ntqSinhVien> ntqSinhVien { get; set; }
    }
}
