//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtqBaiKiemTraGiuaKi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NtqK22CNT1Lesson07bEntities : DbContext
    {
        public NtqK22CNT1Lesson07bEntities()
            : base("name=NtqK22CNT1Lesson07bEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ntqKhoa> ntqKhoa { get; set; }
        public virtual DbSet<ntqSinhVien> ntqSinhVien { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
