//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtqBaiKiemTraGiuaKi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NtqSinhVien
    {
        public string NtqMaSV { get; set; }
        public string NtqHoSV { get; set; }
        public string NtqTenSv { get; set; }
        public Nullable<System.DateTime> NtqNgaySinh { get; set; }
        public Nullable<bool> NtqPhai { get; set; }
        public string NtqPhone { get; set; }
        public string NtqEmail { get; set; }
        public string NtqMaKh { get; set; }
        public string NtqMaKhoa { get; set; }
    
        public virtual NtqKhoa NtqKhoa { get; set; }
    }
}
