//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtqBaiKiemTraGiuaKi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NtqK22CNT1Lesoon07bEntities1 : DbContext
    {
        public NtqK22CNT1Lesoon07bEntities1()
            : base("name=NtqK22CNT1Lesoon07bEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NtqKhoa> NtqKhoa { get; set; }
        public virtual DbSet<NtqSinhVien> NtqSinhVien { get; set; }
    }
}
