//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtqK22CNT1Lesson11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NtqTaiKhoan
    {
        public int NtqId { get; set; }
        public string NtqUserName { get; set; }
        public string NtqPassword { get; set; }
        public string NtqFullName { get; set; }
        public Nullable<int> NtqAge { get; set; }
        public string NtqEmail { get; set; }
        public string NtqPhone { get; set; }
        public Nullable<bool> NtqStatus { get; set; }
    }
}
